# Site settings
title: PaperBon.net
email: info@paperbon.net
description: "Website of PaperBon.net publisher."
baseurl: "/paperbonnet"
url: "http://paperbon.net"
username: "papermaster"

# Serve settings
host: 0.0.0.0

# Build settings
markdown: kramdown
permalink: pretty

#GitHub defaults
safe: true
lsi: false

#Vagrant settings
exclude: [Vagrantfile, README.md]
